[theme]
base = "light"
primaryColor = "#1F8068"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = false
